import "server-only";

import { getRepoFile } from "@/lib/github-content";
import { hermesChat } from "@/lib/hermes-client";
import { loadMadrigalConfig } from "@/lib/madrigal/config";
import { upsertContextFile } from "@/lib/madrigal/context-writer";
import { getIdMap, setState } from "@/lib/madrigal/id-map";

const MADRIGAL_REPO = "juliantedstone/context-message-madrigal";

export type SpecOutcome =
  | { status: "done" }
  | { reason: string; status: "skipped" };

const WHY_INSTRUCTIONS =
  "You are answering a job application's 'Why do you want to work here?' question for Julian Tedstone. Using the role + employer research provided, write a specific, sincere 120-180 word answer in his voice (direct, British English, no hype). Return the answer text only — no preamble, no markdown headings.";

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => `${pad}${line}`)
    .join("\n");
}

/**
 * Build form-spec.yaml per contracts/form-spec.schema.yaml. Profile fields are
 * known; the "why" answer is generated; CSS selectors + the full field set come
 * from the live ATS page and are therefore TEMPLATED here — real selector
 * discovery is a submit-stage (Phase 3) concern. Attachments reference the
 * docket assets produced by adapt.
 */
function buildFormSpec(input: {
  roleUid: string;
  applicationUrl: string;
  applyingEmail: string;
  galleryCode: string;
  companySlug: string;
  why: string;
}): string {
  return `# Generated by the madrigal spec stage. SELECTORS ARE TEMPLATED —
# the submit worker (Phase 3) resolves real selectors against the live ATS page.
role_uid: ${input.roleUid}
application_url: ${input.applicationUrl || "TODO"}
ats: unknown            # greenhouse | lever | ashby | workday | unknown

fields:
  - selector: "TODO:first_name"
    label: First name
    type: text
    value: Julian
    source: profile
    required: true
  - selector: "TODO:last_name"
    label: Last name
    type: text
    value: Tedstone
    source: profile
    required: true
  - selector: "TODO:email"
    label: Email
    type: email
    value: ${input.applyingEmail}
    source: profile
    required: true
  - selector: "TODO:why"
    label: Why do you want to work here?
    type: longtext
    source: generated
    confidence: 0.7
    required: true
    value: |
${indent(input.why, 6)}

attachments:
  - field: "TODO:resume"
    asset: docket://${input.galleryCode}/${input.companySlug}/variant-cv.pdf
  - field: "TODO:cover_letter"
    asset: docket://${input.galleryCode}/${input.companySlug}/cover-letter.pdf

submit:
  button: "TODO:submit"
  expect_ack_email: true
  ack_match: ["${input.companySlug}", "application received", "thanks for applying"]

result:
  submitted_at:
  confirmation_text:
  evidence: []
  status:
`;
}

/**
 * Spec stage — `adapting` -> `ready`. Generates the application's free-text
 * answer(s) via hermes and assembles form-spec.yaml into the role's submission
 * dir. Skipped (caller may retry) if hermes is unavailable.
 */
export async function runSpec(roleUid: string): Promise<SpecOutcome> {
  const row = await getIdMap(roleUid);
  if (!row) {
    return { reason: "unknown role", status: "skipped" };
  }
  const dir = row.contextPath ?? "";
  if (!dir) {
    return { reason: "no context path", status: "skipped" };
  }

  let context = "";
  for (const file of ["role.md", "research.md"]) {
    try {
      context += `${(await getRepoFile(MADRIGAL_REPO, `${dir}/${file}`)).content}\n\n`;
    } catch {
      // degraded — proceed with whatever is present
    }
  }

  const why = await hermesChat({
    instructions: WHY_INSTRUCTIONS,
    message: context || "(no context available)",
  });
  if (!why) {
    return { reason: "hermes unavailable", status: "skipped" };
  }

  const config = await loadMadrigalConfig();
  const meta = row.meta as { applicationUrl?: string };
  const formSpec = buildFormSpec({
    applicationUrl: meta.applicationUrl ?? "",
    applyingEmail: config.identity.applyingEmail,
    companySlug: row.companySlug ?? "",
    galleryCode: config.identity.galleryCode,
    roleUid,
    why,
  });

  await upsertContextFile(
    `${dir}/submission/form-spec.yaml`,
    formSpec,
    `madrigal: spec form-spec ${roleUid}`
  );

  await setState(roleUid, "ready", "nozero", "adapting");
  return { status: "done" };
}
